resources/lib/dbupdate.py
I have implemented my suggested code from the bug report and also
rearranged the code slightly to make it more efficient.
=> Fix for issue #240 - Max folder depth bug

resources/emu_autoconfig.xml, resources/lib/dialogeditromcollection.py, resources/lib/emulatorautoconfig/autoconfig.py, resources/lib/wizardconfigxml.py, resources/tests/test_autoconfig.py, resources/tests/testdata/test_emu_autoconfig.xml, resources/tests/testdata/test_emu_autoconfig_empty.xml
Add code to support OSX in emu autoconfig (for both Add and Edit Rom Collection) as per #245 
Also add Android Atari 7800 and ZX Spectrum as per #236
=> Fix for Issue #245, #236 Autoconfig support for mac

resources/lib/dialoggameinfo.py, resources/lib/gui.py, resources/skins/Default/720p/script-RCB-gameinfo.xml, resources/skins/Default/720p/script-Rom_Collection_Browser-main.xml, resources/skins/Night/720p/script-Rom_Collection_Browser-main.xml, resources/skins/Simplicity/720p/script-Rom_Collection_Browser-main.xml
Change reference in skin XML files from ListItem.Property to ListItem.Art
Remove deprecated parameters from ListItem call, and add them as setArt parameters
=> Use setArt for images rather than setProperty

resources/tests/test_autoconfig.py, resources/tests/test_config.py, resources/tests/test_config_filetype.py, resources/tests/test_config_romcollection.py, resources/tests/test_config_scraper.py, resources/tests/test_db_upgrade.py, resources/tests/test_dbupdate.py, resources/tests/test_pyscraper.py, resources/tests/test_scrapers.py, resources/tests/test_scrapers_artwork.py
PEP formatting
Import using path
Mark some tests to skip as they are not ready yet
Skip tests that retrieve from websites and APIs for the time being - need to add response HTML as test data for consistency
=> Fix test classes

resources/lib/pyscraper/pyscraper.py, resources/tests/test_pyscraper.py
Some refactoring for pyscraper and unit tests
=> pyscraper refactoring

resources/lib/pyscraper/descriptionparser.py, resources/lib/pyscraper/descriptionparserflatfile.py, resources/lib/pyscraper/descriptionparserxml.py
* Refactor parsing GameGrammar XML file
* Move code to read metadata from file/URL to separate functions
=> Refactoring for parsing metadata

resources/lib/dbupdate.py
This avoids the entire game from not being added to the DB if the NFO write fails
=> Add exception handling around NFO write

resources/lib/dbupdate.py, resources/lib/gui.py, resources/lib/util.py
Move code to retrieve scraper mode closer to where it is used in dbupdate
Remove redundant parameter being passed across a number of functions
=> Move scrape mode settings retrieval

resources/lib/dbupdate.py
=> Include import

resources/lib/TestDataBase/config.xml, resources/lib/config.py, resources/lib/configxmlwriter.py
=> Remove references to Xbox-specific attributes

resources/lib/dbupdate.py, resources/lib/helper.py, resources/lib/nfowriter.py, resources/tests/test_config_romcollection.py
Move function from helper.py to romcollection object
Remove redundant imports
=> Move gamename from filename function

resources/lib/config.py
Forgot to include this in last merge
=> Include function moved from helper.py but not actually committed

addon.xml
=> Require Kodi Krypton Python APIs

resources/lib/pyscraper/thegamesdb_scraper.py, resources/tests/test_scrapers_thegamesdb.py
Key for game name is Game, not Name
Add unit test
=> Fix key for game name

resources/lib/pyscraper/giantbomb_scraper.py, resources/lib/pyscraper/thegamesdb_scraper.py, resources/lib/pyscraper/web_scraper.py
Fix date handling when date format doesn't work (sometimes returns None, resulting in a TypeError exception)
Move function to parent class
=> Fix date handling

resources/lib/dbupdate.py
Remove unused parameters from function call and remove redundant function
=> Refactor scraping - remove redundant parameters

resources/lib/nfowriter.py
Additional logging
Move duplicate code into loops
Functions to break up long code sequences
=> Refactor game NFO writing

resources/lib/dbupdate.py, resources/lib/gui.py
Remove some functions
Don't pass settings object around
Reduce number of parameters passed to functions
=> Refactor dbupdate function calls

resources/lib/dialoggameinfo.py, resources/lib/gui.py, resources/lib/helper.py, resources/lib/temptests.py
load images dynamically instead of storing paths in database
=> Imageloading

addon.xml
Apps which emulate a game system is restricted at the Microsoft Store. 
please don't publish the add-on with `<platform>all</platform>` or we will have to remove the add-on from the Kodi's repositories.
=> don't allow install add-on on uwp platform.

convert_skin_files.py, default.py, resources/lib/config.py, resources/lib/configxmlupdater.py, resources/lib/configxmlwriter.py, resources/lib/dbupdate.py, resources/lib/dialoggameinfo.py, resources/lib/emulatorautoconfig/autoconfig.py, resources/lib/gamedatabase.py, resources/lib/gui.py, resources/lib/launcher.py, resources/lib/nfowriter.py, resources/lib/pyscraper/mame_scraper.py, resources/lib/pyscraper/matcher.py, resources/lib/pyscraper/mobygames_scraper.py, resources/lib/pyscraper/thegamesdb_scraper_legacy.py, resources/lib/util.py, resources/lib/wizardconfigxml.py, resources/tests/test_autoconfig.py, resources/tests/test_convert_skinfiles.py, resources/tests/test_db_gameview.py, resources/tests/test_dbupdate.py, resources/tests/test_imageloading.py, resources/tests/test_scrapers_giantbomb.py, resources/tests/test_scrapers_mobygames.py, resources/tests/test_scrapers_offline_gdbi.py, resources/tests/test_scrapers_thegamesdb_legacy.py
- Exception, exc --> Exception as exc
- print "" --> print ("")
- from module import *
- str.decode()
=> python 3 migration
